apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhoooop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhoooop 
  name: rhoooop
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhoooop 
